### ISSUE TITLE
Can Seq++ polyphony be used for programming a multi-voice melody?

### ISSUE THREAD

**Issue by freddyz** [squinkylabs/SquinkyVCV#160]
I'm wondering if a single instance of Seq++ set to 2 channels of polyphony can be used for a 2-part melody?  Meaning, poly gate/CV channel 1 always outputs "voice A", and channel 2 always outputs the "voice B".  It seems that the default behavior is... not exactly this.

Really cool module, by the way!  This is my first time playing with it and the interface seems very efficient for programming in a long melody.

**Comment by squinkylabs** [comment]
No, you can't do that. The FAQ talks about this: https://github.com/squinkylabs/SquinkyVCV/blob/main/docs/sq-faq.md#im-trying-to-make-certain-notes-go-to-certain-voices-in-vcv

Since that FAQ predates the 4X4 module it does not mention that it's easy to do this by putting the two parts into two different "tracks" of 4X4.

Other than this "limitation", I'm glad you are enjoying Seq++

**Comment by freddyz** [comment]
The FAQ is pretty clear I should have checked it out first.  Thanks for the reply, have a good one!

**Comment by squinkylabs** [comment]
haha - we really don't expect everyone to read every scrap of documentation, so no worries ;-)
