### ISSUE TITLE
output dropoff in Kitchen Sync.

### ISSUE THREAD

**Issue by almostEric** [squinkylabs/SquinkyVCV#192]
If you crank the Kitchen Sync's Octave control to 10, the output drops from 5v ptp to <1. The Ratio control has the same effect if the Octave is pretty high (and can take the output to 0)

**Comment by squinkylabs** [comment]
You mean when you set the pitch above 10 (fs/4)? Yes, it certainly does. and it you take it all the way to 20k, there is almost nothing. Thank goodness, right? Of course any VCO that doesn't alias like crazy it going to have to make some compromises re top octave response, aliasing, and CPU usage. Many of our modules do start rolling off above 10k. It might not be the "optimal" compromise, but it is intentional.

**Comment by almostEric** [comment]
I understand that you *really* care about aliasing. I just find it an odd behavior that instead of limiting the frequency of the vco to the range you want, that the vco essentially shuts off. I also wonder what the purpose is of having the Octave control going to 10 if the VCO doesn't support it. Your deal though

**Comment by squinkylabs** [comment]
Thank you for your kind interest. I think maybe you misunderstood?

You are correct that when the user sets the VCO to higher than 20k that kitchen sink fades out, and it would be an alternative to have it say stick at 15k. I think I prefer fading out but it's of course something on which reasonable minds could disagree.

The control goes up to 10 in case a user wanted to counteract a strongly negative input to one of the other pitch inputs - the combination could then be in the usable range. I can certainly see a point that the octave setting of 10 is not that useful. But luckily the user does not have to set it there if they don't want to.
