### ISSUE TITLE
Feature Request: Set threshold in Squinky COMP in terms of decibels

### ISSUE THREAD

**Issue by Chaircrusher** [squinkylabs/SquinkyVCV#198]
When I use compressors I often use an mathematical mode for setting controls.
1. Set the threshold to a level that produces desired gain reduction.
2. Set the makeup gain based on the average gain reduction (as reported by the gain reduction meter)

I can do that, but there's one thing missing: the threshold is an abstract voltage. Does that correspond to the linear voltage of the input? That isn't a useful measurement for threshold; it would be better if it was log-scaled and the units were decibels below 0dB.

**Comment by squinkylabs** [comment]
That's a good point. Will have to look into that.

**Comment by squinkylabs** [comment]
"the threshold is an abstract voltage". Actually it isn't abstract at all. VCV uses voltages all the time. So, while db is more familiar,absolute voltaige is very tangible and well defined.

But back to db.

**Comment by squinkylabs** [comment]
I assume you would like the VCV standard where 0dB is +/- 10 volts? btw, expressing the threshold in volts, while not as familiar as DB, is completely unambiguous, and not "abstract" at all.

**Comment by Chaircrusher** [comment]
I'm looking at it from the point of view of music production.  Any meter I look at on real hardware measures gain reduction in terms of decibels below 0dB - -6dB corresponds to 50% reduction in amplitude. 

I like your compressor a lot, and I have no trouble using it as is.  Just saying that if the gain reduction knob and gain reduction display were calibrated in decibels it would be friendlier to people used to working in those units.

**Comment by squinkylabs** [comment]
oh, I totally agree. and, btw, the meters proper are in decibels, and you are correct that for a gain reduction decibels are completely unambiguous. (I think the meters are 2db per section).

It's when absolute levels are concerned that decibel is ambiguous, and absolute level is what the threshold is. It is the absolute level at which the gain reduction will kick in.

To be unambiguous, decibels also need you to specify a definition of what 0 db is in absolute level. That's what DBv is for. In VCV Andrew has defined 0 db as +/- 10v, so that is what I will use (even thought if it were up to me I would probably call 10v +20 or +12 db. But that's an ancient argument (see k-20 and k-12 metering standards, although you probably already know about this.)

**Comment by squinkylabs** [comment]
This is now fixed, starting with version 1.0.19.
