### ISSUE TITLE
Poly Gate Output in Seq++

### ISSUE THREAD

**Issue by midiguru** [squinkylabs/SquinkyVCV#98]
Doing a test on Seq++. Nothing musical in the attached patch file, just random notes. There's something odd happening with the poly gate output in certain situations. If you run this sequence, you'll hear that the note at bar 3, beat 3, has a filter attack, while none of the other notes do. This is evidently because the ADSR is failing to assign a new voice to the new note. I was originally using the Nysthi Poly ADSR, and it did the same thing, so I think the problem may be in Seq++. You can see the glitch in both of the Scopes.

Changing the polyphony setting or various note lengths will sometimes move the problem to a different note, or eliminate it.

This module is a great addition to VCV. Thanks for your hard work on it!
[piano_roll_test.zip](https://github.com/squinkylabs/SquinkyVCV/files/3586853/piano_roll_test.zip)

**Comment by squinkylabs** [comment]
This is with the new version that's in the plugin manager?

**Comment by midiguru** [comment]
1.0.4. Downloaded this morning from the plugin manager.

**Comment by squinkylabs** [comment]
Yes, listening to your clip I do hear the issue. Seem like a bug to me, but it will take some digging to figure it out. As an experiment, I did change your clocks from X4 (16th note) to X16 (64th note) and the problem goes away. So it's related to the way your clip is 16th notes that are (in effect) being quantized to 16th notes due to the clock resolution. For sure it sounds like a bug, but using a higher resolution clock will avoid any issues around quantization.

**Comment by squinkylabs** [comment]
There was a bug in the the voice assignment. Fixed in 1.0.5
